# Generated by Django 4.2.7 on 2024-01-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cloud/files')),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
