# Generated by Django 4.2.7 on 2023-12-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=50)),
                ('read_status', models.CharField(default='unread', max_length=10)),
                ('msg_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
