# Generated by Django 4.2.7 on 2023-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_desc_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='read_status',
            field=models.CharField(default='unread', max_length=6),
        ),
    ]
