# Generated by Django 4.2.7 on 2023-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
