# Generated by Django 4.2.7 on 2023-12-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='update',
            new_name='update_desc',
        ),
    ]
