# Generated by Django 4.2.7 on 2023-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_update_orderupdate_update_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
